/* eslint-disable max-lines */
const COLO_TO_CITY: Record<string, string> = {
  ABJ: 'Abidjan',
  ABQ: 'Albuquerque',
  ACC: 'Accra',
  ADD: 'Addis Ababa',
  ADL: 'Adelaide',
  AGP: 'Malaga',
  AKL: 'Auckland',
  AMA: 'Amsterdam',
  ANR: 'Antwerp',
  ARN: 'Stockholm',
  ASB: 'Ashgabat',
  ATH: 'Athens',
  ATL: 'Atlanta',
  AUC: 'Abu Dhabi',
  AUS: 'Austin',
  AZR: 'Agadir',
  BDL: 'Hartford',
  BEG: 'Belgrade',
  BEL: 'Belem',
  BER: 'Berlin',
  BHX: 'Birmingham',
  BJS: 'Beijing',
  BKK: 'Bangkok',
  BKO: 'Bamako',
  BLR: 'Bangalore',
  BNA: 'Nashville',
  BNE: 'Brisbane',
  BOD: 'Bordeaux',
  BOG: 'Bogota',
  BOM: 'Mumbai',
  BOS: 'Boston',
  BRE: 'Bremen',
  BRN: 'Bern',
  BRS: 'Bristol',
  BRU: 'Brussels',
  BSB: 'Brasilia',
  BUE: 'Buenos Aires',
  BWI: 'Baltimore',
  CAI: 'Cairo',
  CAN: 'Guangzhou',
  CBV: 'Caracas',
  CGK: 'Jakarta',
  CGN: 'Cologne',
  CHC: 'Christchurch',
  CHS: 'Charleston',
  CKG: 'Chongqing',
  CLE: 'Cleveland',
  CLL: 'College Station',
  CLT: 'Charlotte',
  CMB: 'Colombo',
  CMH: 'Columbus',
  CNF: 'Belo Horizonte',
  CNS: 'Cairns',
  CPH: 'Copenhagen',
  CRK: 'Angeles City',
  CCS: 'Caracas',
  CTS: 'Sapporo',
  CTU: 'Chengdu',
  CWL: 'Cardiff',
  DAD: 'Da Nang',
  DAL: 'Dallas',
  DAR: 'Dar es Salaam',
  DAY: 'Dayton',
  DCA: 'Washington',
  DEN: 'Denver',
  DFY: 'Deyang',
  DHA: 'Dhahran',
  DME: 'Moscow',
  DMM: 'Dammam',
  DOH: 'Doha',
  DRW: 'Darwin',
  DSL: 'Dijon',
  DTW: 'Detroit',
  DUB: 'Dublin',
  DUR: 'Durban',
  DXB: 'Dubai',
  EDI: 'Edinburgh',
  EIN: 'Eindhoven',
  EMA: 'East Midlands',
  ENA: 'Nairobi',
  EWR: 'Newark',
  EZE: 'Buenos Aires',
  FAI: 'Fairbanks',
  FCO: 'Rome',
  FLR: 'Florence',
  FNA: 'Freetown',
  FOR: 'Fortaleza',
  FRA: 'Frankfurt',
  FRB: 'Friebourg',
  FUK: 'Fukuoka',
  GDL: 'Guadalajara',
  GEO: 'Georgetown',
  GLA: 'Glasgow',
  GND: 'Geneva',
  GIG: 'Rio de Janeiro',
  GUA: 'Guatemala City',
  GUM: 'Guam',
  GVA: 'Geneva',
  HAM: 'Hamburg',
  HAN: 'Hanoi',
  HAQ: 'Haifa',
  HAU: 'Haugesund',
  HDY: 'Hat Yai',
  HEL: 'Helsinki',
  HER: 'Heraklion',
  HKG: 'Hong Kong',
  HKT: 'Phuket',
  HNL: 'Honolulu',
  HOR: 'Horta',
  HPN: 'White Plains',
  HRB: 'Harbin',
  HRE: 'Harare',
  HSV: 'Huntsville',
  HYD: 'Hyderabad',
  IAD: 'Washington',
  IAH: 'Houston',
  ICN: 'Seoul',
  IKA: 'Tehran',
  IND: 'Indianapolis',
  ISB: 'Islamabad',
  IST: 'Istanbul',
  ITM: 'Osaka',
  JAN: 'Jackson',
  JIB: 'Djibouti',
  JNB: 'Johannesburg',
  KAN: 'Kano',
  KBF: 'Kobe',
  KHI: 'Karachi',
  KIN: 'Kingston',
  KIV: 'Chisinau',
  KIX: 'Osaka',
  KRK: 'Krakow',
  KRT: 'Khartoum',
  KTM: 'Kathmandu',
  KUL: 'Kuala Lumpur',
  KWE: 'Guiyang',
  LAS: 'Las Vegas',
  LAX: 'Los Angeles',
  LCA: 'Larnaca',
  LCY: 'London',
  LED: 'St. Petersburg',
  LFW: 'Lome',
  LHR: 'London',
  LIS: 'Lisbon',
  LLW: 'Lilongwe',
  LYS: 'Lyon',
  MAA: 'Chennai',
  MAD: 'Madrid',
  MAN: 'Manchester',
  MBA: 'Mombasa',
  MBX: 'Mombasa',
  MCI: 'Kansas City',
  MCO: 'Orlando',
  MDT: 'Middletown',
  MED: 'Medina',
  MEL: 'Melbourne',
  MEM: 'Memphis',
  MEX: 'Mexico City',
  MFM: 'Macau',
  MGA: 'Managua',
  MIA: 'Miami',
  MIL: 'Milan',
  MKC: 'Kansas City',
  MLA: 'Malta',
  MLE: 'Male',
  MLU: 'Monroe',
  MNL: 'Manila',
  MOS: 'Moscow',
  MPM: 'Maputo',
  MRU: 'Mauritius',
  MRS: 'Marseille',
  MRSA: 'Mar del Plata',
  MSP: 'Minneapolis',
  MSQ: 'Minsk',
  MSY: 'New Orleans',
  MTJ: 'Montrose',
  MUC: 'Munich',
  MXP: 'Milan',
  NAP: 'Naples',
  NAS: 'Nassau',
  NAT: 'Natal',
  NBO: 'Nairobi',
  NCE: 'Nice',
  NCL: 'Newcastle',
  NGO: 'Nagoya',
  NKC: 'Nouakchott',
  NLK: 'Norfolk Island',
  NNG: 'Nanning',
  NRT: 'Tokyo',
  NTE: 'Nantes',
  NVS: 'Novosibirsk',
  OAK: 'Oakland',
  OKC: 'Oklahoma City',
  OMA: 'Omaha',
  OPO: 'Porto',
  ORY: 'Paris',
  OSL: 'Oslo',
  OTP: 'Bucharest',
  OVD: 'Asturias',
  PAP: 'Port-au-Prince',
  PAE: 'Everett',
  PBI: 'West Palm Beach',
  PDX: 'Portland',
  PEO: 'Perugia',
  PER: 'Perth',
  PHX: 'Phoenix',
  PHL: 'Philadelphia',
  PKC: 'Poznan',
  PMI: 'Palma',
  PNQ: 'Pune',
  POS: 'Port of Spain',
  PRG: 'Prague',
  PSA: 'Pisa',
  PTY: 'Panama City',
  PTP: 'Pointe-a-Pitre',
  PUQ: 'Punta Arenas',
  PUS: 'Busan',
  PVD: 'Providence',
  PVG: 'Shanghai',
  RDU: 'Raleigh',
  REC: 'Recife',
  RGN: 'Yangon',
  RIC: 'Richmond',
  RKV: 'Reykjavik',
  RNA: 'Reno',
  ROB: 'Monrovia',
  ROC: 'Rochester',
  ROV: 'Rostov-on-Don',
  RPR: 'Raipur',
  RSW: 'Fort Myers',
  RUH: 'Riyadh',
  RUN: 'Reunion',
  SAO: 'Sao Paulo',
  SAT: 'San Antonio',
  SCL: 'Santiago',
  SCQ: 'Santiago de Compostela',
  SEA: 'Seattle',
  SFO: 'San Francisco',
  SGN: 'Ho Chi Minh City',
  SHA: 'Shanghai',
  SHJ: 'Sharjah',
  SIN: 'Singapore',
  SJU: 'San Juan',
  SKG: 'Thessaloniki',
  SLC: 'Salt Lake City',
  SOF: 'Sofia',
  SOU: 'Southampton',
  SPG: 'Saint Petersburg',
  SPN: 'Saipan',
  SRQ: 'Sarasota',
  SSD: 'Sousse',
  SSH: 'Sharm El Sheikh',
  STN: 'London',
  STR: 'Stuttgart',
  SUB: 'Surabaya',
  SVG: 'Stavanger',
  SVO: 'Moscow',
  SWF: 'Newburgh',
  SXB: 'Strasbourg',
  SZG: 'Salzburg',
  SZX: 'Shenzhen',
  TAP: 'Tallahassee',
  TAS: 'Tashkent',
  TBS: 'Tbilisi',
  TFS: 'Tenerife',
  TGD: 'Podgorica',
  TGU: 'Tegucigalpa',
  THR: 'Tehran',
  TIA: 'Tirana',
  TIP: 'Tripoli',
  TLV: 'Tel Aviv',
  TNA: 'Jinan',
  TLS: 'Toulouse',
  TLY: 'Touly',
  TNR: 'Antananarivo',
  TPE: 'Taipei',
  TRD: 'Trondheim',
  TRV: 'Thiruvananthapuram',
  TSA: 'Taipei',
  TSN: 'Tianjin',
  TUL: 'Tulsa',
  TUN: 'Tunis',
  TUS: 'Tucson',
  TXL: 'Berlin',
  UIO: 'Quito',
  VAC: 'Vatican City',
  VCE: 'Venice',
  VIE: 'Vienna',
  VKO: 'Moscow',
  VNO: 'Vilnius',
  VOZ: 'Voronezh',
  VRN: 'Verona',
  WAW: 'Warsaw',
  WLG: 'Wellington',
  WRO: 'Wroclaw',
  XIY: "Xi'an",
  YAM: 'Sudbury',
  YAZ: 'Tofino',
  YBR: 'Brandon',
  YCB: 'Cambridge Bay',
  YCD: 'Nanaimo',
  YCG: 'Castlegar',
  YCL: 'Charlo',
  YCY: 'Clyde River',
  YDF: 'Deer Lake',
  YEG: 'Edmonton',
  YEV: 'Inuvik',
  YFB: 'Iqaluit',
  YFC: 'Fredericton',
  YGH: 'Fort Good Hope',
  YGP: 'Gaspé',
  YGR: 'Îles-de-la-Madeleine',
  YGY: 'Kangiqsualujjuaq',
  YHM: 'Hamilton',
  YHO: 'Hopedale',
  YHZ: 'Halifax',
  YIK: 'Ivujivik',
  YIO: 'Pond Inlet',
  YJT: 'Stephenville',
  YKA: 'Kamloops',
  YKC: 'Kindersley',
  YKM: 'Kelowna',
  YKF: 'Kitchener',
  YLB: 'Lac Brochet',
  YLW: 'Kelowna',
  YMM: 'Fort McMurray',
  YMO: 'Moosonee',
  YMX: 'Montreal',
  YNA: 'Natashquan',
  YNE: 'Norway House',
  YOC: 'Old Crow',
  YOG: 'Ogoki Post',
  YOW: 'Ottawa',
  YPB: 'Port Alberni',
  YPC: 'Prince Albert',
  YPD: 'Pickle Lake',
  YPF: 'Port-Menier',
  YPH: 'Inukjuak',
  YPK: 'Pitt Meadows',
  YPL: 'Pickle Lake',
  YPM: 'Poste-de-la-Baleine',
  YPR: 'Prince Rupert',
  YPT: 'Puvirnituq',
  YQB: 'Quebec City',
  YQG: 'Windsor',
  YQK: 'Kangiqsujuaq',
  YQM: 'Moncton',
  YQR: 'Regina',
  YQT: 'Timmins',
  YQU: 'Grande Prairie',
  YQV: 'Yorkton',
  YQW: 'North Battleford',
  YQX: 'Gander',
  YQY: 'Sydney',
  YRB: 'Resolute',
  YRF: 'Kangiqsualujjuaq',
  YRG: 'Gaspé',
  YSB: 'Sudbury',
  YSC: 'Sherbrooke',
  YSF: 'Sachs Harbour',
  YSK: 'Sanikiluaq',
  YSO: 'Salluit',
  YSQ: 'Schefferville',
  YSR: 'Stony Rapids',
  YST: 'St. Theresa Point',
  YSZ: 'Schefferville',
  YTH: 'Thompson',
  YTK: 'Sanikiluaq',
  YTL: 'Thunder Bay',
  YTR: 'Trenton',
  YTS: 'Timmins',
  YUL: 'Montreal',
  YUT: 'Rankin Inlet',
  YVB: 'Kuujjuaq',
  YVC: 'Yorkton',
  YVR: 'Vancouver',
  YWG: 'Winnipeg',
  YWK: 'Wabush',
  YWM: 'Wabush',
  YWP: 'Whapmagoostui',
  YWY: 'Wetaskiwin',
  YXE: 'Saskatoon',
  YXH: 'Medicine Hat',
  YXJ: 'Fort St. John',
  YXL: 'Sioux Lookout',
  YXM: 'Sydney',
  YXN: 'Norman Wells',
  YXP: 'Pangnirtung',
  YXQ: 'Watson Lake',
  YXR: 'Red Lake',
  YXT: 'Terrace',
  YXU: 'London',
  YXX: 'Abbotsford',
  YXY: 'Whitehorse',
  YYC: 'Calgary',
  YYD: 'Smithers',
  YYF: 'Penticton',
  YYG: 'Charlottetown',
  YYJ: 'Victoria',
  YYQ: 'Churchill',
  YYR: 'Goose Bay',
  YYT: 'St. Johns',
  YYZ: 'Toronto',
  YZF: 'Yellowknife',
  ZAG: 'Zagreb',
  ZAZ: 'Zaragoza',
  ZRH: 'Zurich',
};

export function getCityFromColo(colo: string): string {
  return COLO_TO_CITY[colo] ?? colo;
}
