[phases.setup]
nixPkgs = ['bun']

[phases.install]
cmds = ['bun install --frozen-lockfile']

[phases.build]
cmds = [
  'bun run build',
  'mkdir -p .next/standalone/.next',
  'cp -r .next/static .next/standalone/.next/static',
  'cp -r public .next/standalone/public'
]

[start]
cmd = 'bun .next/standalone/server.js'
